

export const listKhodam = [
    "Harimau Sumatra",
    "Kucing Anggora",
    "Sapi Madura",
    "Babi Ngepet",
    "Kambing",
    "Kuda Poni",
    "Anak Konda",
    "Ayam Tiren",
    "Ikan Cupang",
    "Casing Hp",
    "Charger Iphone",
    "Kabel Ties",
    "Kipas Angin",
    "Rawa Rontek",
    "Sigit Rendang",
    "Martabak Cokelat",
    "Naga Sakti",
    "Ratu Pantai Selatan",
    "Harimau Putih",
    "Raja Jin",
    "Dewi Bulan",
    "Penjaga Hutan",
    "Singa Emas",
    "Banteng Sakti",
    "Elang Perkasa",
    "Laba-laba Sunda",
    "Buaya Hitam",
    "Katak Sigma",
    "Skibidi Sigma",
    "Ikan Lohan Tidak Gyat",
    "Burung Puyuh Warna Bjir",
    "Monyet Hutan",
    "Gajah Ngawi",
    "Kursi Mewing",
    "Balon Ku Sigma",
    "Di Hina Tetap Sigma",
    "Kue Keju",
    "Mobil Bekas Toyota Gyat",
    "Rehan Toyota",
    "Ikbal Hotwil",
    "Kuda Pake Sendal",
    "Sendal ",
    "Jaket Bapak",
    "Kambing Hitam",
    "Pintu Gerbang",
    "Kayu Jati ",
    "Jati Diri",
    "Ayam Tidak Punya KTP",
    "Dino Sok Inggris",
    "Bibir Jontor Badag",
    "Teh Sari Wangi",
    "Indomi Kecap Asin",
    "Burung Elang Dari Jawa",
    "Tidak Ada/Kosong !",
    "Nokia Bapak",
    "Telur Gulung",
    "Sayur Asem Kecap Manis",
    "Baju Terbang",
    "Sendal Jepit",
    "Nasi Padang",
    "Pizza Mewah",
    "Jus Alpukat",
    "Sate Ayam",
    "Gado-Gado",
    "Kambing Guling",
    "Tahu Bulat",
    "Lontong Balap",
    "Soto Ayam",
    "Bakso Gepeng",
    "Cilok Kenyal",
    "Mie Ayam Lezat",
    "Es Cendol Manis",
    "Kopi Hitam Mantap",
    "Brownies Lumer",
    "Kerak Telor",
    "Tempe Mendoan",
    "Jajanan Pasar",
    "Pecel Lele",
    "Ayam Geprek",
    "Roti Bakar",
    "Pisang Goreng",
    "Bubur Ayam",
    "Nasi Goreng Spesial",
    "Sop Buntut",
    "Gule Kambing",
    "Rawon Hitam",
    "Ikan Bakar",
    "Sate Kambing",
    "Kue Cubit",
    "Cakwe",
    "Tahu Gejrot",
    "Kacang Polong",
    "Sayur Bayam",
    "Sambal Terasi",
    "Es Dawet",
    "Teh Tarik",
    "Es Teler",
    "Kerupuk Kulit",
    "Rengginang",
    "Emping Melinjo",
    "Mie Goreng",
    "Risoles",
    "Lumpia Semarang",
    "Pempek Palembang",
    "Asinan Betawi",
    "Lemper Ayam",
    "Bika Ambon",
    "Klepon",
    "Kue Lumpur",
    "Putu Ayu",
    "Onde-Onde",
    "Pukis",
    "Serabi",
    "Martabak Telur",
    "Sempol Ayam",
    "Bubur Ketan Hitam",
    "Kai Cenat",
    "Ibu Kai Cenat",
    "Bapak Kai Cenat",
    "Adek Kai Cenat",
    "Kakak Kai Cenat",
    "Nenek Kai Cenat",
    "Kakek Kai Cenat",
    "Bibi Kai Cenat",
    "Paman Kai Cenat",
    "Istri Kai Cenat",
    "Keponakan Kai Cenat",
    "Bapak Nya Istri Kai Cenat",
    "Istri nya Bapak nya Istri Kai Cenat",
    "Es Dawet Ketan Hitam Pekat Oli Bekas",
    "Kai Cenat Mode Sigma",
    "Bocil Mewing",
    "[Rare,Misterius,Cool,Sigma,Mewing,Made in ohio] Akbar Motor Mio Gas Elpiji Wibu Sejati Kasur Bekas Motor Supra Blukutuk-Blukutuk",
    "Kapten Bajak Laut Ngawi",
    "Mio Mirza",
    "Kak Gem Mode Mewing",
    "Kak Gem",
    "Uni Bakwan",
    "Sambal Goreng Kecap Hitam",
    "Kamu Bukan User Khodam !",
    "Kosong",
    "Ambatron Type 555 - y 9 UZ",
    "Ambatukam Mewing",
    "Mas Rusdi Tidak G4Y",
    "Suki Liar",
    "Suki Type G4",
    "The World",
    "Star Platinum",
    "Gajah"
]
